astraea_add_fuzzer(astraea_elf64_parser_fuzz
    elf64_parser_fuzz.cpp
)
target_link_libraries(astraea_elf64_parser_fuzz PRIVATE Astraea::core)
astraea_set_project_warnings(astraea_elf64_parser_fuzz)

astraea_add_fuzzer(astraea_dynamic_parser_fuzz
    dynamic_parser_fuzz.cpp
)
target_link_libraries(astraea_dynamic_parser_fuzz PRIVATE Astraea::core)
astraea_set_project_warnings(astraea_dynamic_parser_fuzz)

astraea_add_fuzzer(astraea_agc_shader_binary_fuzz
    agc_shader_binary_fuzz.cpp
)
target_link_libraries(astraea_agc_shader_binary_fuzz PRIVATE Astraea::core)
astraea_set_project_warnings(astraea_agc_shader_binary_fuzz)

astraea_add_fuzzer(astraea_agc_shader_container_fuzz
    agc_shader_container_fuzz.cpp
)
target_link_libraries(astraea_agc_shader_container_fuzz PRIVATE Astraea::core)
astraea_set_project_warnings(astraea_agc_shader_container_fuzz)
